// Code generated by MockGen. DO NOT EDIT.
// Source: shopping_cart.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockShoppingCardRepo is a mock of ShoppingCardRepo interface.
type MockShoppingCardRepo struct {
	ctrl     *gomock.Controller
	recorder *MockShoppingCardRepoMockRecorder
}

// MockShoppingCardRepoMockRecorder is the mock recorder for MockShoppingCardRepo.
type MockShoppingCardRepoMockRecorder struct {
	mock *MockShoppingCardRepo
}

// NewMockShoppingCardRepo creates a new mock instance.
func NewMockShoppingCardRepo(ctrl *gomock.Controller) *MockShoppingCardRepo {
	mock := &MockShoppingCardRepo{ctrl: ctrl}
	mock.recorder = &MockShoppingCardRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShoppingCardRepo) EXPECT() *MockShoppingCardRepoMockRecorder {
	return m.recorder
}

// AddAnnouncement mocks base method.
func (m *MockShoppingCardRepo) AddAnnouncement(userID, announcementID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAnnouncement", userID, announcementID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAnnouncement indicates an expected call of AddAnnouncement.
func (mr *MockShoppingCardRepoMockRecorder) AddAnnouncement(userID, announcementID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAnnouncement", reflect.TypeOf((*MockShoppingCardRepo)(nil).AddAnnouncement), userID, announcementID)
}

// DeleteAnnouncement mocks base method.
func (m *MockShoppingCardRepo) DeleteAnnouncement(userID, announcementID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAnnouncement", userID, announcementID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAnnouncement indicates an expected call of DeleteAnnouncement.
func (mr *MockShoppingCardRepoMockRecorder) DeleteAnnouncement(userID, announcementID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAnnouncement", reflect.TypeOf((*MockShoppingCardRepo)(nil).DeleteAnnouncement), userID, announcementID)
}

// GetByUserID mocks base method.
func (m *MockShoppingCardRepo) GetByUserID(userID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockShoppingCardRepoMockRecorder) GetByUserID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockShoppingCardRepo)(nil).GetByUserID), userID)
}
