version: '3.9'

services:
  app:
    build: .
    container_name: go_app
    ports:
      - "8080:8080"
    environment:
      - ENV=production
    volumes:
      - .:/app
    working_dir: /app
    command: ["/root/main"]
    depends_on:
      postgres_db1:
        condition: service_healthy  

  postgres_db1:
    image: postgres:latest
    container_name: postgres_db1
    restart: always
    environment:
      POSTGRES_DB: database1
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
    ports:
      - "5433:5432"
    volumes:
      - postgres_db1_data:/var/lib/postgresql/data
      - ./db_migration/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user1 -d database1"]
      interval: 5s  
      timeout: 5s    
      retries: 5     
      start_period: 3s  

volumes:
  postgres_db1_data:
