services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - shared-network
    depends_on:
      db:
        condition: service_healthy  

  db:
    image: postgres:17
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: love
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db_migration/*:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d store"]
      interval: 5s  
      timeout: 5s    
      retries: 5     
      start_period: 3s
    networks:
      - shared-network

volumes:
  db_data:

networks:
  shared-network:
    name: shared-network
    external: false