services:
  app:
#    image: golang:1.23
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    networks:
      - shared-network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:17
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: love
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d store"]
      interval: 5s  
      timeout: 5s    
      retries: 5     
      start_period: 3s
    networks:
      - shared-network

  redis:
    image: redis
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'
    command: [ "redis-server", "--appendonly", "yes" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - shared-network

volumes:
  db_data:
  redis_data:

networks:
  shared-network:
    name: shared-network
    external: false