FROM golang:1.23-alpine AS builder

RUN apk update && apk add --no-cache git

WORKDIR /app

COPY . .

RUN go mod download && go build -o /app/analytics ./cmd/analytics/main.go

FROM alpine:latest

RUN apk --no-cache add ca-certificates

COPY --from=builder /app/analytics /app/analytics
COPY --from=builder /app/config/analytics-config.yaml /app/config/analytics-config.yaml

WORKDIR /app

EXPOSE 8082

CMD ["./analytics"]