db:
  login: postgres
  password: love
  port: 5432
  database: store
  host: db
es:
  index: "announcements"
etl_search_timeout: 1m
max_open_conns: 10
secret: mysuperpupermegaultraSecret
srv_port: :8080
session_duration: 1h
