name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop
      - 'feature/**'

permissions:
  contents: read

jobs:
  build:
    name: Build, Test, and Lint
    runs-on: ubuntu-latest

    steps:
      - name: setup
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'

      - name: build
        run: | 
          go mod download
          go build -v ./...

      - name: tests
        run: go test -v ./...

      - name: linter
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
          $(go env GOPATH)/bin/golangci-lint run --config .golint.yaml
